### ISSUE TITLE
Invalid CSS generated when using !important rules

### ISSUE THREAD

**Issue by gravitystorm** [mzsanford/R2rb#18]
The following CSS is incorrectly converted, since the `!important` rule needs to stay at the end:

```ruby
R2.r2("div { border-radius: 2 !important}")
=> "div{border-radius:!important 2;}"
```

The upstream nodejs version of r2 doesn't have this same issue. [It has some code to explicitly handle `!important`](https://github.com/ded/R2/blob/dbc72c1bd0b37c27eb01e216cc9fc4f792c54371/r2.js#L139-L152), but I don't profess to understand how that works!

```bash
$ echo 'div { border-radius: 2 !important;}' | yarn run r2
div{border-radius:2 !important;}
```

**Comment by mzsanford** [comment]
Fixed in main (https://github.com/mzsanford/R2rb/commit/2ea49e090ac7fbcf2b4faf56739dd4361d6c010d) and publishing version 0.2.8 with the change now. The use of `!important` is problematic with this sort of automatic transformation since the purpose of this code is to _change_ the value that someone deemed `!important`. Having said that generating invalid CSS is worse so I fixed it.

**Comment by gravitystorm** [comment]
Great, thank you @mzsanford !
